package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * AirportTaxi generated by hbm2java
 */
public class AirportTaxi  extends BaseBean{


     private Integer airportTaxiId;
     private PerKmRate perKmRate;

    public AirportTaxi() {
    }

    public AirportTaxi(PerKmRate perKmRate) {
       this.perKmRate = perKmRate;
    }
   
    public Integer getAirportTaxiId() {
        return this.airportTaxiId;
    }
    
    public void setAirportTaxiId(Integer airportTaxiId) {
        this.airportTaxiId = airportTaxiId;
    }
    public PerKmRate getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(PerKmRate perKmRate) {
        this.perKmRate = perKmRate;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


