package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * AreaMaster generated by hbm2java
 */
public class AreaMaster  extends BaseBean {


     private Integer areaMasterId;
     private CityMaster cityMaster;
     private String areaName;
     private String longitude;
     private String latitude;
     private Set taxiTicketTransactions = new HashSet(0);
     private Set airportTransactionsForPickupAreaMasterId = new HashSet(0);
     private Set outstationTransactions = new HashSet(0);
     private Set busTransactionsForDropAreaMasterId = new HashSet(0);
     private Set airportTransactionsForDropAreaMasterId = new HashSet(0);
     private Set ptopTransactionsForDropAreaMasterId = new HashSet(0);
     private Set bikeTransactions = new HashSet(0);
     private Set ptopTransactionsForPickupAreaMasterId = new HashSet(0);
     private Set caronrentTransactions = new HashSet(0);
     private Set busTransactionsForPickupAreaMasterId = new HashSet(0);

    public AreaMaster() {
    }

	
    public AreaMaster(CityMaster cityMaster, String areaName, String longitude, String latitude) {
        this.cityMaster = cityMaster;
        this.areaName = areaName;
        this.longitude = longitude;
        this.latitude = latitude;
    }
    public AreaMaster(CityMaster cityMaster, String areaName, String longitude, String latitude, Set taxiTicketTransactions, Set airportTransactionsForPickupAreaMasterId, Set outstationTransactions, Set busTransactionsForDropAreaMasterId, Set airportTransactionsForDropAreaMasterId, Set ptopTransactionsForDropAreaMasterId, Set bikeTransactions, Set ptopTransactionsForPickupAreaMasterId, Set caronrentTransactions, Set busTransactionsForPickupAreaMasterId) {
       this.cityMaster = cityMaster;
       this.areaName = areaName;
       this.longitude = longitude;
       this.latitude = latitude;
       this.taxiTicketTransactions = taxiTicketTransactions;
       this.airportTransactionsForPickupAreaMasterId = airportTransactionsForPickupAreaMasterId;
       this.outstationTransactions = outstationTransactions;
       this.busTransactionsForDropAreaMasterId = busTransactionsForDropAreaMasterId;
       this.airportTransactionsForDropAreaMasterId = airportTransactionsForDropAreaMasterId;
       this.ptopTransactionsForDropAreaMasterId = ptopTransactionsForDropAreaMasterId;
       this.bikeTransactions = bikeTransactions;
       this.ptopTransactionsForPickupAreaMasterId = ptopTransactionsForPickupAreaMasterId;
       this.caronrentTransactions = caronrentTransactions;
       this.busTransactionsForPickupAreaMasterId = busTransactionsForPickupAreaMasterId;
    }
   
    public Integer getAreaMasterId() {
        return this.areaMasterId;
    }
    
    public void setAreaMasterId(Integer areaMasterId) {
        this.areaMasterId = areaMasterId;
    }
    public CityMaster getCityMaster() {
        return this.cityMaster;
    }
    
    public void setCityMaster(CityMaster cityMaster) {
        this.cityMaster = cityMaster;
    }
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }
    public Set getTaxiTicketTransactions() {
        return this.taxiTicketTransactions;
    }
    
    public void setTaxiTicketTransactions(Set taxiTicketTransactions) {
        this.taxiTicketTransactions = taxiTicketTransactions;
    }
    public Set getAirportTransactionsForPickupAreaMasterId() {
        return this.airportTransactionsForPickupAreaMasterId;
    }
    
    public void setAirportTransactionsForPickupAreaMasterId(Set airportTransactionsForPickupAreaMasterId) {
        this.airportTransactionsForPickupAreaMasterId = airportTransactionsForPickupAreaMasterId;
    }
    public Set getOutstationTransactions() {
        return this.outstationTransactions;
    }
    
    public void setOutstationTransactions(Set outstationTransactions) {
        this.outstationTransactions = outstationTransactions;
    }
    public Set getBusTransactionsForDropAreaMasterId() {
        return this.busTransactionsForDropAreaMasterId;
    }
    
    public void setBusTransactionsForDropAreaMasterId(Set busTransactionsForDropAreaMasterId) {
        this.busTransactionsForDropAreaMasterId = busTransactionsForDropAreaMasterId;
    }
    public Set getAirportTransactionsForDropAreaMasterId() {
        return this.airportTransactionsForDropAreaMasterId;
    }
    
    public void setAirportTransactionsForDropAreaMasterId(Set airportTransactionsForDropAreaMasterId) {
        this.airportTransactionsForDropAreaMasterId = airportTransactionsForDropAreaMasterId;
    }
    public Set getPtopTransactionsForDropAreaMasterId() {
        return this.ptopTransactionsForDropAreaMasterId;
    }
    
    public void setPtopTransactionsForDropAreaMasterId(Set ptopTransactionsForDropAreaMasterId) {
        this.ptopTransactionsForDropAreaMasterId = ptopTransactionsForDropAreaMasterId;
    }
    public Set getBikeTransactions() {
        return this.bikeTransactions;
    }
    
    public void setBikeTransactions(Set bikeTransactions) {
        this.bikeTransactions = bikeTransactions;
    }
    public Set getPtopTransactionsForPickupAreaMasterId() {
        return this.ptopTransactionsForPickupAreaMasterId;
    }
    
    public void setPtopTransactionsForPickupAreaMasterId(Set ptopTransactionsForPickupAreaMasterId) {
        this.ptopTransactionsForPickupAreaMasterId = ptopTransactionsForPickupAreaMasterId;
    }
    public Set getCaronrentTransactions() {
        return this.caronrentTransactions;
    }
    
    public void setCaronrentTransactions(Set caronrentTransactions) {
        this.caronrentTransactions = caronrentTransactions;
    }
    public Set getBusTransactionsForPickupAreaMasterId() {
        return this.busTransactionsForPickupAreaMasterId;
    }
    
    public void setBusTransactionsForPickupAreaMasterId(Set busTransactionsForPickupAreaMasterId) {
        this.busTransactionsForPickupAreaMasterId = busTransactionsForPickupAreaMasterId;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


