package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * BusDetails generated by hbm2java
 */
public class BusDetails  extends BaseBean {


     private Integer busDetailsId;
     private BusType busType;
     private PartnerDetails partnerDetails;
     private String busTittle;
     private int noOfSeat;
     private int perKmRate;
     private int waitingChargeHour;
     private String busImage;
     private String busNumber;
     private byte enableForTicker;
     private String note;

    public BusDetails() {
    }

    public BusDetails(BusType busType, PartnerDetails partnerDetails, String busTittle, int noOfSeat, int perKmRate, int waitingChargeHour, String busImage, String busNumber, byte enableForTicker, String note) {
       this.busType = busType;
       this.partnerDetails = partnerDetails;
       this.busTittle = busTittle;
       this.noOfSeat = noOfSeat;
       this.perKmRate = perKmRate;
       this.waitingChargeHour = waitingChargeHour;
       this.busImage = busImage;
       this.busNumber = busNumber;
       this.enableForTicker = enableForTicker;
       this.note = note;
    }
   
    public Integer getBusDetailsId() {
        return this.busDetailsId;
    }
    
    public void setBusDetailsId(Integer busDetailsId) {
        this.busDetailsId = busDetailsId;
    }
    public BusType getBusType() {
        return this.busType;
    }
    
    public void setBusType(BusType busType) {
        this.busType = busType;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public String getBusTittle() {
        return this.busTittle;
    }
    
    public void setBusTittle(String busTittle) {
        this.busTittle = busTittle;
    }
    public int getNoOfSeat() {
        return this.noOfSeat;
    }
    
    public void setNoOfSeat(int noOfSeat) {
        this.noOfSeat = noOfSeat;
    }
    public int getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(int perKmRate) {
        this.perKmRate = perKmRate;
    }
    public int getWaitingChargeHour() {
        return this.waitingChargeHour;
    }
    
    public void setWaitingChargeHour(int waitingChargeHour) {
        this.waitingChargeHour = waitingChargeHour;
    }
    public String getBusImage() {
        return this.busImage;
    }
    
    public void setBusImage(String busImage) {
        this.busImage = busImage;
    }
    public String getBusNumber() {
        return this.busNumber;
    }
    
    public void setBusNumber(String busNumber) {
        this.busNumber = busNumber;
    }
    public byte getEnableForTicker() {
        return this.enableForTicker;
    }
    
    public void setEnableForTicker(byte enableForTicker) {
        this.enableForTicker = enableForTicker;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


