package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * BusType generated by hbm2java
 */
public class BusType  extends BaseBean {


     private Integer busTypeId;
     private String busType;
     private String description;
     private Set busDetailses = new HashSet(0);

    public BusType() {
    }

	
    public BusType(String busType, String description) {
        this.busType = busType;
        this.description = description;
    }
    public BusType(String busType, String description, Set busDetailses) {
       this.busType = busType;
       this.description = description;
       this.busDetailses = busDetailses;
    }
   
    public Integer getBusTypeId() {
        return this.busTypeId;
    }
    
    public void setBusTypeId(Integer busTypeId) {
        this.busTypeId = busTypeId;
    }
    public String getBusType() {
        return this.busType;
    }
    
    public void setBusType(String busType) {
        this.busType = busType;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Set getBusDetailses() {
        return this.busDetailses;
    }
    
    public void setBusDetailses(Set busDetailses) {
        this.busDetailses = busDetailses;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


