package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * BusTransaction generated by hbm2java
 */
public class BusTransaction  extends BaseBean {


     private Integer busTransactionId;
     private CityMaster cityMasterByDestinationCityId;
     private AreaMaster areaMasterByPickupAreaMasterId;
     private CityMaster cityMasterBySouceCityId;
     private AreaMaster areaMasterByDropAreaMasterId;
     private PartnerDetails partnerDetails;
     private CustomerRegistration customerRegistration;
     private Date pickupTime;
     private Date date;
     private String note;
     private double estimateKm;
     private double estimateCost;
     private Date estimateTime;

    public BusTransaction() {
    }

    public BusTransaction(CityMaster cityMasterByDestinationCityId, AreaMaster areaMasterByPickupAreaMasterId, CityMaster cityMasterBySouceCityId, AreaMaster areaMasterByDropAreaMasterId, PartnerDetails partnerDetails, CustomerRegistration customerRegistration, Date pickupTime, Date date, String note, double estimateKm, double estimateCost, Date estimateTime) {
       this.cityMasterByDestinationCityId = cityMasterByDestinationCityId;
       this.areaMasterByPickupAreaMasterId = areaMasterByPickupAreaMasterId;
       this.cityMasterBySouceCityId = cityMasterBySouceCityId;
       this.areaMasterByDropAreaMasterId = areaMasterByDropAreaMasterId;
       this.partnerDetails = partnerDetails;
       this.customerRegistration = customerRegistration;
       this.pickupTime = pickupTime;
       this.date = date;
       this.note = note;
       this.estimateKm = estimateKm;
       this.estimateCost = estimateCost;
       this.estimateTime = estimateTime;
    }
   
    public Integer getBusTransactionId() {
        return this.busTransactionId;
    }
    
    public void setBusTransactionId(Integer busTransactionId) {
        this.busTransactionId = busTransactionId;
    }
    public CityMaster getCityMasterByDestinationCityId() {
        return this.cityMasterByDestinationCityId;
    }
    
    public void setCityMasterByDestinationCityId(CityMaster cityMasterByDestinationCityId) {
        this.cityMasterByDestinationCityId = cityMasterByDestinationCityId;
    }
    public AreaMaster getAreaMasterByPickupAreaMasterId() {
        return this.areaMasterByPickupAreaMasterId;
    }
    
    public void setAreaMasterByPickupAreaMasterId(AreaMaster areaMasterByPickupAreaMasterId) {
        this.areaMasterByPickupAreaMasterId = areaMasterByPickupAreaMasterId;
    }
    public CityMaster getCityMasterBySouceCityId() {
        return this.cityMasterBySouceCityId;
    }
    
    public void setCityMasterBySouceCityId(CityMaster cityMasterBySouceCityId) {
        this.cityMasterBySouceCityId = cityMasterBySouceCityId;
    }
    public AreaMaster getAreaMasterByDropAreaMasterId() {
        return this.areaMasterByDropAreaMasterId;
    }
    
    public void setAreaMasterByDropAreaMasterId(AreaMaster areaMasterByDropAreaMasterId) {
        this.areaMasterByDropAreaMasterId = areaMasterByDropAreaMasterId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public Date getPickupTime() {
        return this.pickupTime;
    }
    
    public void setPickupTime(Date pickupTime) {
        this.pickupTime = pickupTime;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public double getEstimateKm() {
        return this.estimateKm;
    }
    
    public void setEstimateKm(double estimateKm) {
        this.estimateKm = estimateKm;
    }
    public double getEstimateCost() {
        return this.estimateCost;
    }
    
    public void setEstimateCost(double estimateCost) {
        this.estimateCost = estimateCost;
    }
    public Date getEstimateTime() {
        return this.estimateTime;
    }
    
    public void setEstimateTime(Date estimateTime) {
        this.estimateTime = estimateTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


