package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitShippingTransaction generated by hbm2java
 */
public class CommitShippingTransaction  extends BaseBean {


     private Integer commitShippingTransactionId;
     private DriverDetails driverDetails;
     private ShippingTransaction shippingTransaction;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitShippingTransaction() {
    }

    public CommitShippingTransaction(DriverDetails driverDetails, ShippingTransaction shippingTransaction, double totalTime, double totalCost, Date commitTime) {
       this.driverDetails = driverDetails;
       this.shippingTransaction = shippingTransaction;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitShippingTransactionId() {
        return this.commitShippingTransactionId;
    }
    
    public void setCommitShippingTransactionId(Integer commitShippingTransactionId) {
        this.commitShippingTransactionId = commitShippingTransactionId;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public ShippingTransaction getShippingTransaction() {
        return this.shippingTransaction;
    }
    
    public void setShippingTransaction(ShippingTransaction shippingTransaction) {
        this.shippingTransaction = shippingTransaction;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


