package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitPackageTransaction generated by hbm2java
 */
public class CommitPackageTransaction  extends BaseBean {


     private Integer commitPackageTransactionId;
     private DriverDetails driverDetails;
     private int packageTransactionId;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitPackageTransaction() {
    }

    public CommitPackageTransaction(DriverDetails driverDetails, int packageTransactionId, double totalTime, double totalCost, Date commitTime) {
       this.driverDetails = driverDetails;
       this.packageTransactionId = packageTransactionId;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitPackageTransactionId() {
        return this.commitPackageTransactionId;
    }
    
    public void setCommitPackageTransactionId(Integer commitPackageTransactionId) {
        this.commitPackageTransactionId = commitPackageTransactionId;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public int getPackageTransactionId() {
        return this.packageTransactionId;
    }
    
    public void setPackageTransactionId(int packageTransactionId) {
        this.packageTransactionId = packageTransactionId;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


