package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitMoversTransaction generated by hbm2java
 */
public class CommitMoversTransaction  extends BaseBean {


     private Integer commitMoversTransactionId;
     private MoversTransaction moversTransaction;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitMoversTransaction() {
    }

    public CommitMoversTransaction(MoversTransaction moversTransaction, double totalTime, double totalCost, Date commitTime) {
       this.moversTransaction = moversTransaction;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitMoversTransactionId() {
        return this.commitMoversTransactionId;
    }
    
    public void setCommitMoversTransactionId(Integer commitMoversTransactionId) {
        this.commitMoversTransactionId = commitMoversTransactionId;
    }
    public MoversTransaction getMoversTransaction() {
        return this.moversTransaction;
    }
    
    public void setMoversTransaction(MoversTransaction moversTransaction) {
        this.moversTransaction = moversTransaction;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


