package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitTaxiTicketTransaction generated by hbm2java
 */
public class CommitTaxiTicketTransaction  extends BaseBean {


     private Integer commitTaxiTicketTransaction;
     private DriverDetails driverDetails;
     private TaxiTicketTransaction taxiTicketTransaction;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitTaxiTicketTransaction() {
    }

    public CommitTaxiTicketTransaction(DriverDetails driverDetails, TaxiTicketTransaction taxiTicketTransaction, double totalTime, double totalCost, Date commitTime) {
       this.driverDetails = driverDetails;
       this.taxiTicketTransaction = taxiTicketTransaction;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitTaxiTicketTransaction() {
        return this.commitTaxiTicketTransaction;
    }
    
    public void setCommitTaxiTicketTransaction(Integer commitTaxiTicketTransaction) {
        this.commitTaxiTicketTransaction = commitTaxiTicketTransaction;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public TaxiTicketTransaction getTaxiTicketTransaction() {
        return this.taxiTicketTransaction;
    }
    
    public void setTaxiTicketTransaction(TaxiTicketTransaction taxiTicketTransaction) {
        this.taxiTicketTransaction = taxiTicketTransaction;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


