package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * CommitBusTransaction generated by hbm2java
 */
public class CommitBusTransaction  extends BaseBean {


     private Integer commitBusTransaction;
     private int busTransactionId;

    public CommitBusTransaction() {
    }

    public CommitBusTransaction(int busTransactionId) {
       this.busTransactionId = busTransactionId;
    }
   
    public Integer getCommitBusTransaction() {
        return this.commitBusTransaction;
    }
    
    public void setCommitBusTransaction(Integer commitBusTransaction) {
        this.commitBusTransaction = commitBusTransaction;
    }
    public int getBusTransactionId() {
        return this.busTransactionId;
    }
    
    public void setBusTransactionId(int busTransactionId) {
        this.busTransactionId = busTransactionId;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


