package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitOutstationTransaction generated by hbm2java
 */
public class CommitOutstationTransaction  extends BaseBean {


     private Integer commitOutstationTransactionId;
     private OutstationTransaction outstationTransaction;
     private DriverDetails driverDetails;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitOutstationTransaction() {
    }

    public CommitOutstationTransaction(OutstationTransaction outstationTransaction, DriverDetails driverDetails, double totalTime, double totalCost, Date commitTime) {
       this.outstationTransaction = outstationTransaction;
       this.driverDetails = driverDetails;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitOutstationTransactionId() {
        return this.commitOutstationTransactionId;
    }
    
    public void setCommitOutstationTransactionId(Integer commitOutstationTransactionId) {
        this.commitOutstationTransactionId = commitOutstationTransactionId;
    }
    public OutstationTransaction getOutstationTransaction() {
        return this.outstationTransaction;
    }
    
    public void setOutstationTransaction(OutstationTransaction outstationTransaction) {
        this.outstationTransaction = outstationTransaction;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


