package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitAirportTransaction generated by hbm2java
 */
public class CommitAirportTransaction  extends BaseBean {


     private Integer commitAirportTransactionId;
     private DriverDetails driverDetails;
     private AirportTransaction airportTransaction;
     private double totalTime;
     private double totalCost;
     private Date commitTime;

    public CommitAirportTransaction() {
    }

    public CommitAirportTransaction(DriverDetails driverDetails, AirportTransaction airportTransaction, double totalTime, double totalCost, Date commitTime) {
       this.driverDetails = driverDetails;
       this.airportTransaction = airportTransaction;
       this.totalTime = totalTime;
       this.totalCost = totalCost;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitAirportTransactionId() {
        return this.commitAirportTransactionId;
    }
    
    public void setCommitAirportTransactionId(Integer commitAirportTransactionId) {
        this.commitAirportTransactionId = commitAirportTransactionId;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public AirportTransaction getAirportTransaction() {
        return this.airportTransaction;
    }
    
    public void setAirportTransaction(AirportTransaction airportTransaction) {
        this.airportTransaction = airportTransaction;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


