package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CommitPtopTransaction generated by hbm2java
 */
public class CommitPtopTransaction  extends BaseBean {


     private Integer commitPtopTransactionId;
     private PtopTransaction ptopTransaction;
     private DriverDetails driverDetails;
     private double totalCost;
     private double totalTime;
     private Date commitTime;

    public CommitPtopTransaction() {
    }

    public CommitPtopTransaction(PtopTransaction ptopTransaction, DriverDetails driverDetails, double totalCost, double totalTime, Date commitTime) {
       this.ptopTransaction = ptopTransaction;
       this.driverDetails = driverDetails;
       this.totalCost = totalCost;
       this.totalTime = totalTime;
       this.commitTime = commitTime;
    }
   
    public Integer getCommitPtopTransactionId() {
        return this.commitPtopTransactionId;
    }
    
    public void setCommitPtopTransactionId(Integer commitPtopTransactionId) {
        this.commitPtopTransactionId = commitPtopTransactionId;
    }
    public PtopTransaction getPtopTransaction() {
        return this.ptopTransaction;
    }
    
    public void setPtopTransaction(PtopTransaction ptopTransaction) {
        this.ptopTransaction = ptopTransaction;
    }
    public DriverDetails getDriverDetails() {
        return this.driverDetails;
    }
    
    public void setDriverDetails(DriverDetails driverDetails) {
        this.driverDetails = driverDetails;
    }
    public double getTotalCost() {
        return this.totalCost;
    }
    
    public void setTotalCost(double totalCost) {
        this.totalCost = totalCost;
    }
    public double getTotalTime() {
        return this.totalTime;
    }
    
    public void setTotalTime(double totalTime) {
        this.totalTime = totalTime;
    }
    public Date getCommitTime() {
        return this.commitTime;
    }
    
    public void setCommitTime(Date commitTime) {
        this.commitTime = commitTime;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


