package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * CustomerLoginDetails generated by hbm2java
 */
public class CustomerLoginDetails  extends BaseBean {


     private Integer customerLoginId;
     private Date timestamp;
     private CustomerRegistration customerRegistration;
     private String ip;
     private String location;

    public CustomerLoginDetails() {
    }

    public CustomerLoginDetails(CustomerRegistration customerRegistration, String ip, String location) {
       this.customerRegistration = customerRegistration;
       this.ip = ip;
       this.location = location;
    }
   
    public Integer getCustomerLoginId() {
        return this.customerLoginId;
    }
    
    public void setCustomerLoginId(Integer customerLoginId) {
        this.customerLoginId = customerLoginId;
    }
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


