package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DeviceDetails generated by hbm2java
 */
public class DeviceDetails  extends BaseBean {


     private Integer deviceDetailsId;
     private TaxiDetails taxiDetails;
     private String location;
     private Set deviceLocations = new HashSet(0);

    public DeviceDetails() {
    }

	
    public DeviceDetails(TaxiDetails taxiDetails, String location) {
        this.taxiDetails = taxiDetails;
        this.location = location;
    }
    public DeviceDetails(TaxiDetails taxiDetails, String location, Set deviceLocations) {
       this.taxiDetails = taxiDetails;
       this.location = location;
       this.deviceLocations = deviceLocations;
    }
   
    public Integer getDeviceDetailsId() {
        return this.deviceDetailsId;
    }
    
    public void setDeviceDetailsId(Integer deviceDetailsId) {
        this.deviceDetailsId = deviceDetailsId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Set getDeviceLocations() {
        return this.deviceLocations;
    }
    
    public void setDeviceLocations(Set deviceLocations) {
        this.deviceLocations = deviceLocations;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


