package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * DriverDetails generated by hbm2java
 */
public class DriverDetails  extends BaseBean {


     private Integer driverDetailsId;
     private PartnerDetails partnerDetails;
     private String firstName;
     private String lastName;
     private String email;
     private String password;
     private String address;
     private String image;
     private String drivingLicenceNo;
     private String electionCardNo;
     private String lightBillNo;
     private String panCardNo;
     private String mobileNo;
     private String registrationNo;
     private Set commitAirportTransactions = new HashSet(0);
     private Set commitShippingTransactions = new HashSet(0);
     private Set commitOutstationTransactions = new HashSet(0);
     private Set commitTaxiTicketTransactions = new HashSet(0);
     private Set commitPtopTransactions = new HashSet(0);
     private Set commitPackageTransactions = new HashSet(0);

    public DriverDetails() {
    }

	
    public DriverDetails(PartnerDetails partnerDetails, String firstName, String lastName, String email, String password, String address, String image, String drivingLicenceNo, String electionCardNo, String lightBillNo, String panCardNo, String mobileNo, String registrationNo) {
        this.partnerDetails = partnerDetails;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
        this.password = password;
        this.address = address;
        this.image = image;
        this.drivingLicenceNo = drivingLicenceNo;
        this.electionCardNo = electionCardNo;
        this.lightBillNo = lightBillNo;
        this.panCardNo = panCardNo;
        this.mobileNo = mobileNo;
        this.registrationNo = registrationNo;
    }
    public DriverDetails(PartnerDetails partnerDetails, String firstName, String lastName, String email, String password, String address, String image, String drivingLicenceNo, String electionCardNo, String lightBillNo, String panCardNo, String mobileNo, String registrationNo, Set commitAirportTransactions, Set commitShippingTransactions, Set commitOutstationTransactions, Set commitTaxiTicketTransactions, Set commitPtopTransactions, Set commitPackageTransactions) {
       this.partnerDetails = partnerDetails;
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.password = password;
       this.address = address;
       this.image = image;
       this.drivingLicenceNo = drivingLicenceNo;
       this.electionCardNo = electionCardNo;
       this.lightBillNo = lightBillNo;
       this.panCardNo = panCardNo;
       this.mobileNo = mobileNo;
       this.registrationNo = registrationNo;
       this.commitAirportTransactions = commitAirportTransactions;
       this.commitShippingTransactions = commitShippingTransactions;
       this.commitOutstationTransactions = commitOutstationTransactions;
       this.commitTaxiTicketTransactions = commitTaxiTicketTransactions;
       this.commitPtopTransactions = commitPtopTransactions;
       this.commitPackageTransactions = commitPackageTransactions;
    }
   
    public Integer getDriverDetailsId() {
        return this.driverDetailsId;
    }
    
    public void setDriverDetailsId(Integer driverDetailsId) {
        this.driverDetailsId = driverDetailsId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getDrivingLicenceNo() {
        return this.drivingLicenceNo;
    }
    
    public void setDrivingLicenceNo(String drivingLicenceNo) {
        this.drivingLicenceNo = drivingLicenceNo;
    }
    public String getElectionCardNo() {
        return this.electionCardNo;
    }
    
    public void setElectionCardNo(String electionCardNo) {
        this.electionCardNo = electionCardNo;
    }
    public String getLightBillNo() {
        return this.lightBillNo;
    }
    
    public void setLightBillNo(String lightBillNo) {
        this.lightBillNo = lightBillNo;
    }
    public String getPanCardNo() {
        return this.panCardNo;
    }
    
    public void setPanCardNo(String panCardNo) {
        this.panCardNo = panCardNo;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getRegistrationNo() {
        return this.registrationNo;
    }
    
    public void setRegistrationNo(String registrationNo) {
        this.registrationNo = registrationNo;
    }
    public Set getCommitAirportTransactions() {
        return this.commitAirportTransactions;
    }
    
    public void setCommitAirportTransactions(Set commitAirportTransactions) {
        this.commitAirportTransactions = commitAirportTransactions;
    }
    public Set getCommitShippingTransactions() {
        return this.commitShippingTransactions;
    }
    
    public void setCommitShippingTransactions(Set commitShippingTransactions) {
        this.commitShippingTransactions = commitShippingTransactions;
    }
    public Set getCommitOutstationTransactions() {
        return this.commitOutstationTransactions;
    }
    
    public void setCommitOutstationTransactions(Set commitOutstationTransactions) {
        this.commitOutstationTransactions = commitOutstationTransactions;
    }
    public Set getCommitTaxiTicketTransactions() {
        return this.commitTaxiTicketTransactions;
    }
    
    public void setCommitTaxiTicketTransactions(Set commitTaxiTicketTransactions) {
        this.commitTaxiTicketTransactions = commitTaxiTicketTransactions;
    }
    public Set getCommitPtopTransactions() {
        return this.commitPtopTransactions;
    }
    
    public void setCommitPtopTransactions(Set commitPtopTransactions) {
        this.commitPtopTransactions = commitPtopTransactions;
    }
    public Set getCommitPackageTransactions() {
        return this.commitPackageTransactions;
    }
    
    public void setCommitPackageTransactions(Set commitPackageTransactions) {
        this.commitPackageTransactions = commitPackageTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


