package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * GoodsType generated by hbm2java
 */
public class GoodsType  extends BaseBean {


     private Integer goodsTypeId;
     private String goodsType;
     private Set shippingTransactions = new HashSet(0);

    public GoodsType() {
    }

	
    public GoodsType(String goodsType) {
        this.goodsType = goodsType;
    }
    public GoodsType(String goodsType, Set shippingTransactions) {
       this.goodsType = goodsType;
       this.shippingTransactions = shippingTransactions;
    }
   
    public Integer getGoodsTypeId() {
        return this.goodsTypeId;
    }
    
    public void setGoodsTypeId(Integer goodsTypeId) {
        this.goodsTypeId = goodsTypeId;
    }
    public String getGoodsType() {
        return this.goodsType;
    }
    
    public void setGoodsType(String goodsType) {
        this.goodsType = goodsType;
    }
    public Set getShippingTransactions() {
        return this.shippingTransactions;
    }
    
    public void setShippingTransactions(Set shippingTransactions) {
        this.shippingTransactions = shippingTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


