package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * LogisticType generated by hbm2java
 */
public class LogisticType  extends BaseBean {


     private Integer logisticTypeId;
     private String logisticType;
     private Set moversTransactions = new HashSet(0);

    public LogisticType() {
    }

	
    public LogisticType(String logisticType) {
        this.logisticType = logisticType;
    }
    public LogisticType(String logisticType, Set moversTransactions) {
       this.logisticType = logisticType;
       this.moversTransactions = moversTransactions;
    }
   
    public Integer getLogisticTypeId() {
        return this.logisticTypeId;
    }
    
    public void setLogisticTypeId(Integer logisticTypeId) {
        this.logisticTypeId = logisticTypeId;
    }
    public String getLogisticType() {
        return this.logisticType;
    }
    
    public void setLogisticType(String logisticType) {
        this.logisticType = logisticType;
    }
    public Set getMoversTransactions() {
        return this.moversTransactions;
    }
    
    public void setMoversTransactions(Set moversTransactions) {
        this.moversTransactions = moversTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


