package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * MoversRate generated by hbm2java
 */
public class MoversRate  extends BaseBean {


     private Integer moversRateId;
     private PerKgRate perKgRate;
     private PerKmRate perKmRate;
     private PartnerDetails partnerDetails;
     private Set moversTransactions = new HashSet(0);

    public MoversRate() {
    }

	
    public MoversRate(PerKgRate perKgRate, PerKmRate perKmRate, PartnerDetails partnerDetails) {
        this.perKgRate = perKgRate;
        this.perKmRate = perKmRate;
        this.partnerDetails = partnerDetails;
    }
    public MoversRate(PerKgRate perKgRate, PerKmRate perKmRate, PartnerDetails partnerDetails, Set moversTransactions) {
       this.perKgRate = perKgRate;
       this.perKmRate = perKmRate;
       this.partnerDetails = partnerDetails;
       this.moversTransactions = moversTransactions;
    }
   
    public Integer getMoversRateId() {
        return this.moversRateId;
    }
    
    public void setMoversRateId(Integer moversRateId) {
        this.moversRateId = moversRateId;
    }
    public PerKgRate getPerKgRate() {
        return this.perKgRate;
    }
    
    public void setPerKgRate(PerKgRate perKgRate) {
        this.perKgRate = perKgRate;
    }
    public PerKmRate getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(PerKmRate perKmRate) {
        this.perKmRate = perKmRate;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public Set getMoversTransactions() {
        return this.moversTransactions;
    }
    
    public void setMoversTransactions(Set moversTransactions) {
        this.moversTransactions = moversTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


