package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * MoversTransaction generated by hbm2java
 */
public class MoversTransaction  extends BaseBean {


     private Integer moversTransactionId;
     private CityMaster cityMasterByStartCityId;
     private CityMaster cityMasterByEndCityId;
     private PartnerDetails partnerDetails;
     private ShippingType shippingType;
     private CustomerRegistration customerRegistration;
     private MoversRate moversRate;
     private LogisticType logisticType;
     private Date date;
     private Date time;
     private String estimateKm;
     private double estimateCost;
     private String pickupAddress;
     private String dropAddress;
     private Set commitMoversTransactions = new HashSet(0);

    public MoversTransaction() {
    }

	
    public MoversTransaction(CityMaster cityMasterByStartCityId, CityMaster cityMasterByEndCityId, PartnerDetails partnerDetails, ShippingType shippingType, CustomerRegistration customerRegistration, MoversRate moversRate, LogisticType logisticType, Date date, Date time, String estimateKm, double estimateCost, String pickupAddress, String dropAddress) {
        this.cityMasterByStartCityId = cityMasterByStartCityId;
        this.cityMasterByEndCityId = cityMasterByEndCityId;
        this.partnerDetails = partnerDetails;
        this.shippingType = shippingType;
        this.customerRegistration = customerRegistration;
        this.moversRate = moversRate;
        this.logisticType = logisticType;
        this.date = date;
        this.time = time;
        this.estimateKm = estimateKm;
        this.estimateCost = estimateCost;
        this.pickupAddress = pickupAddress;
        this.dropAddress = dropAddress;
    }
    public MoversTransaction(CityMaster cityMasterByStartCityId, CityMaster cityMasterByEndCityId, PartnerDetails partnerDetails, ShippingType shippingType, CustomerRegistration customerRegistration, MoversRate moversRate, LogisticType logisticType, Date date, Date time, String estimateKm, double estimateCost, String pickupAddress, String dropAddress, Set commitMoversTransactions) {
       this.cityMasterByStartCityId = cityMasterByStartCityId;
       this.cityMasterByEndCityId = cityMasterByEndCityId;
       this.partnerDetails = partnerDetails;
       this.shippingType = shippingType;
       this.customerRegistration = customerRegistration;
       this.moversRate = moversRate;
       this.logisticType = logisticType;
       this.date = date;
       this.time = time;
       this.estimateKm = estimateKm;
       this.estimateCost = estimateCost;
       this.pickupAddress = pickupAddress;
       this.dropAddress = dropAddress;
       this.commitMoversTransactions = commitMoversTransactions;
    }
   
    public Integer getMoversTransactionId() {
        return this.moversTransactionId;
    }
    
    public void setMoversTransactionId(Integer moversTransactionId) {
        this.moversTransactionId = moversTransactionId;
    }
    public CityMaster getCityMasterByStartCityId() {
        return this.cityMasterByStartCityId;
    }
    
    public void setCityMasterByStartCityId(CityMaster cityMasterByStartCityId) {
        this.cityMasterByStartCityId = cityMasterByStartCityId;
    }
    public CityMaster getCityMasterByEndCityId() {
        return this.cityMasterByEndCityId;
    }
    
    public void setCityMasterByEndCityId(CityMaster cityMasterByEndCityId) {
        this.cityMasterByEndCityId = cityMasterByEndCityId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public ShippingType getShippingType() {
        return this.shippingType;
    }
    
    public void setShippingType(ShippingType shippingType) {
        this.shippingType = shippingType;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public MoversRate getMoversRate() {
        return this.moversRate;
    }
    
    public void setMoversRate(MoversRate moversRate) {
        this.moversRate = moversRate;
    }
    public LogisticType getLogisticType() {
        return this.logisticType;
    }
    
    public void setLogisticType(LogisticType logisticType) {
        this.logisticType = logisticType;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public String getEstimateKm() {
        return this.estimateKm;
    }
    
    public void setEstimateKm(String estimateKm) {
        this.estimateKm = estimateKm;
    }
    public double getEstimateCost() {
        return this.estimateCost;
    }
    
    public void setEstimateCost(double estimateCost) {
        this.estimateCost = estimateCost;
    }
    public String getPickupAddress() {
        return this.pickupAddress;
    }
    
    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }
    public String getDropAddress() {
        return this.dropAddress;
    }
    
    public void setDropAddress(String dropAddress) {
        this.dropAddress = dropAddress;
    }
    public Set getCommitMoversTransactions() {
        return this.commitMoversTransactions;
    }
    
    public void setCommitMoversTransactions(Set commitMoversTransactions) {
        this.commitMoversTransactions = commitMoversTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


