package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * OutstationTransaction generated by hbm2java
 */
public class OutstationTransaction  extends BaseBean {


     private Integer outstationTransactionId;
     private TaxiDetails taxiDetails;
     private CityMaster cityMasterByEndCityMasterId;
     private AreaMaster areaMaster;
     private PartnerDetails partnerDetails;
     private CustomerRegistration customerRegistration;
     private CityMaster cityMasterByStartCityMasterId;
     private Date date;
     private String pickupAddress;
     private Date pickupTime;
     private String note;
     private double estimateCost;
     private Date estimateTime;
     private double estimateKm;
     private String viaCityMasterId;
     private Set commitOutstationTransactions = new HashSet(0);

    public OutstationTransaction() {
    }

	
    public OutstationTransaction(TaxiDetails taxiDetails, CityMaster cityMasterByEndCityMasterId, AreaMaster areaMaster, PartnerDetails partnerDetails, CustomerRegistration customerRegistration, CityMaster cityMasterByStartCityMasterId, Date date, String pickupAddress, Date pickupTime, String note, double estimateCost, Date estimateTime, double estimateKm, String viaCityMasterId) {
        this.taxiDetails = taxiDetails;
        this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
        this.areaMaster = areaMaster;
        this.partnerDetails = partnerDetails;
        this.customerRegistration = customerRegistration;
        this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
        this.date = date;
        this.pickupAddress = pickupAddress;
        this.pickupTime = pickupTime;
        this.note = note;
        this.estimateCost = estimateCost;
        this.estimateTime = estimateTime;
        this.estimateKm = estimateKm;
        this.viaCityMasterId = viaCityMasterId;
    }
    public OutstationTransaction(TaxiDetails taxiDetails, CityMaster cityMasterByEndCityMasterId, AreaMaster areaMaster, PartnerDetails partnerDetails, CustomerRegistration customerRegistration, CityMaster cityMasterByStartCityMasterId, Date date, String pickupAddress, Date pickupTime, String note, double estimateCost, Date estimateTime, double estimateKm, String viaCityMasterId, Set commitOutstationTransactions) {
       this.taxiDetails = taxiDetails;
       this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
       this.areaMaster = areaMaster;
       this.partnerDetails = partnerDetails;
       this.customerRegistration = customerRegistration;
       this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
       this.date = date;
       this.pickupAddress = pickupAddress;
       this.pickupTime = pickupTime;
       this.note = note;
       this.estimateCost = estimateCost;
       this.estimateTime = estimateTime;
       this.estimateKm = estimateKm;
       this.viaCityMasterId = viaCityMasterId;
       this.commitOutstationTransactions = commitOutstationTransactions;
    }
   
    public Integer getOutstationTransactionId() {
        return this.outstationTransactionId;
    }
    
    public void setOutstationTransactionId(Integer outstationTransactionId) {
        this.outstationTransactionId = outstationTransactionId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public CityMaster getCityMasterByEndCityMasterId() {
        return this.cityMasterByEndCityMasterId;
    }
    
    public void setCityMasterByEndCityMasterId(CityMaster cityMasterByEndCityMasterId) {
        this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
    }
    public AreaMaster getAreaMaster() {
        return this.areaMaster;
    }
    
    public void setAreaMaster(AreaMaster areaMaster) {
        this.areaMaster = areaMaster;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public CityMaster getCityMasterByStartCityMasterId() {
        return this.cityMasterByStartCityMasterId;
    }
    
    public void setCityMasterByStartCityMasterId(CityMaster cityMasterByStartCityMasterId) {
        this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPickupAddress() {
        return this.pickupAddress;
    }
    
    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }
    public Date getPickupTime() {
        return this.pickupTime;
    }
    
    public void setPickupTime(Date pickupTime) {
        this.pickupTime = pickupTime;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public double getEstimateCost() {
        return this.estimateCost;
    }
    
    public void setEstimateCost(double estimateCost) {
        this.estimateCost = estimateCost;
    }
    public Date getEstimateTime() {
        return this.estimateTime;
    }
    
    public void setEstimateTime(Date estimateTime) {
        this.estimateTime = estimateTime;
    }
    public double getEstimateKm() {
        return this.estimateKm;
    }
    
    public void setEstimateKm(double estimateKm) {
        this.estimateKm = estimateKm;
    }
    public String getViaCityMasterId() {
        return this.viaCityMasterId;
    }
    
    public void setViaCityMasterId(String viaCityMasterId) {
        this.viaCityMasterId = viaCityMasterId;
    }
    public Set getCommitOutstationTransactions() {
        return this.commitOutstationTransactions;
    }
    
    public void setCommitOutstationTransactions(Set commitOutstationTransactions) {
        this.commitOutstationTransactions = commitOutstationTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


