package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * PartnerAccountDetails generated by hbm2java
 */
public class PartnerAccountDetails  extends BaseBean {


     private Integer partnerAccountId;
     private PartnerDetails partnerDetails;

    public PartnerAccountDetails() {
    }

    public PartnerAccountDetails(PartnerDetails partnerDetails) {
       this.partnerDetails = partnerDetails;
    }
   
    public Integer getPartnerAccountId() {
        return this.partnerAccountId;
    }
    
    public void setPartnerAccountId(Integer partnerAccountId) {
        this.partnerAccountId = partnerAccountId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


