package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PartnerType generated by hbm2java
 */
public class PartnerType  extends BaseBean {


     private Integer partnerTypeId;
     private String partnerType;
     private Set partnerDetailses = new HashSet(0);

    public PartnerType() {
    }

	
    public PartnerType(String partnerType) {
        this.partnerType = partnerType;
    }
    public PartnerType(String partnerType, Set partnerDetailses) {
       this.partnerType = partnerType;
       this.partnerDetailses = partnerDetailses;
    }
   
    public Integer getPartnerTypeId() {
        return this.partnerTypeId;
    }
    
    public void setPartnerTypeId(Integer partnerTypeId) {
        this.partnerTypeId = partnerTypeId;
    }
    public String getPartnerType() {
        return this.partnerType;
    }
    
    public void setPartnerType(String partnerType) {
        this.partnerType = partnerType;
    }
    public Set getPartnerDetailses() {
        return this.partnerDetailses;
    }
    
    public void setPartnerDetailses(Set partnerDetailses) {
        this.partnerDetailses = partnerDetailses;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


