package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PartnerDetails generated by hbm2java
 */
public class PartnerDetails  extends BaseBean {


     private Integer partnerDetailsId;
     private PartnerType partnerType;
     private String partnerTittle;
     private String firstName;
     private String lastName;
     private String partnerMobile;
     private String partnerEmail;
     private String partnerPassword;
     private String partnerAddress;
     private Set ptopTransactions = new HashSet(0);
     private Set moversRates = new HashSet(0);
     private Set partnerAccountDetailses = new HashSet(0);
     private Set bikeTransactions = new HashSet(0);
     private Set busDetailses = new HashSet(0);
     private Set taxiDetailses = new HashSet(0);
     private Set shippingTransactions = new HashSet(0);
     private Set driverDetailses = new HashSet(0);
     private Set bikeDetailses = new HashSet(0);
     private Set partnerRatingDetailses = new HashSet(0);
     private Set busTransactions = new HashSet(0);
     private Set caronrentTransactions = new HashSet(0);
     private Set outstationTransactions = new HashSet(0);
     private Set airportTransactions = new HashSet(0);
     private Set shippingVehicleDetailses = new HashSet(0);
     private Set perKgRates = new HashSet(0);
     private Set moversTransactions = new HashSet(0);

    public PartnerDetails() {
    }

	
    public PartnerDetails(PartnerType partnerType, String partnerTittle, String firstName, String lastName, String partnerMobile, String partnerEmail, String partnerPassword, String partnerAddress) {
        this.partnerType = partnerType;
        this.partnerTittle = partnerTittle;
        this.firstName = firstName;
        this.lastName = lastName;
        this.partnerMobile = partnerMobile;
        this.partnerEmail = partnerEmail;
        this.partnerPassword = partnerPassword;
        this.partnerAddress = partnerAddress;
    }
    public PartnerDetails(PartnerType partnerType, String partnerTittle, String firstName, String lastName, String partnerMobile, String partnerEmail, String partnerPassword, String partnerAddress, Set ptopTransactions, Set moversRates, Set partnerAccountDetailses, Set bikeTransactions, Set busDetailses, Set taxiDetailses, Set shippingTransactions, Set driverDetailses, Set bikeDetailses, Set partnerRatingDetailses, Set busTransactions, Set caronrentTransactions, Set outstationTransactions, Set airportTransactions, Set shippingVehicleDetailses, Set perKgRates, Set moversTransactions) {
       this.partnerType = partnerType;
       this.partnerTittle = partnerTittle;
       this.firstName = firstName;
       this.lastName = lastName;
       this.partnerMobile = partnerMobile;
       this.partnerEmail = partnerEmail;
       this.partnerPassword = partnerPassword;
       this.partnerAddress = partnerAddress;
       this.ptopTransactions = ptopTransactions;
       this.moversRates = moversRates;
       this.partnerAccountDetailses = partnerAccountDetailses;
       this.bikeTransactions = bikeTransactions;
       this.busDetailses = busDetailses;
       this.taxiDetailses = taxiDetailses;
       this.shippingTransactions = shippingTransactions;
       this.driverDetailses = driverDetailses;
       this.bikeDetailses = bikeDetailses;
       this.partnerRatingDetailses = partnerRatingDetailses;
       this.busTransactions = busTransactions;
       this.caronrentTransactions = caronrentTransactions;
       this.outstationTransactions = outstationTransactions;
       this.airportTransactions = airportTransactions;
       this.shippingVehicleDetailses = shippingVehicleDetailses;
       this.perKgRates = perKgRates;
       this.moversTransactions = moversTransactions;
    }
   
    public Integer getPartnerDetailsId() {
        return this.partnerDetailsId;
    }
    
    public void setPartnerDetailsId(Integer partnerDetailsId) {
        this.partnerDetailsId = partnerDetailsId;
    }
    public PartnerType getPartnerType() {
        return this.partnerType;
    }
    
    public void setPartnerType(PartnerType partnerType) {
        this.partnerType = partnerType;
    }
    public String getPartnerTittle() {
        return this.partnerTittle;
    }
    
    public void setPartnerTittle(String partnerTittle) {
        this.partnerTittle = partnerTittle;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPartnerMobile() {
        return this.partnerMobile;
    }
    
    public void setPartnerMobile(String partnerMobile) {
        this.partnerMobile = partnerMobile;
    }
    public String getPartnerEmail() {
        return this.partnerEmail;
    }
    
    public void setPartnerEmail(String partnerEmail) {
        this.partnerEmail = partnerEmail;
    }
    public String getPartnerPassword() {
        return this.partnerPassword;
    }
    
    public void setPartnerPassword(String partnerPassword) {
        this.partnerPassword = partnerPassword;
    }
    public String getPartnerAddress() {
        return this.partnerAddress;
    }
    
    public void setPartnerAddress(String partnerAddress) {
        this.partnerAddress = partnerAddress;
    }
    public Set getPtopTransactions() {
        return this.ptopTransactions;
    }
    
    public void setPtopTransactions(Set ptopTransactions) {
        this.ptopTransactions = ptopTransactions;
    }
    public Set getMoversRates() {
        return this.moversRates;
    }
    
    public void setMoversRates(Set moversRates) {
        this.moversRates = moversRates;
    }
    public Set getPartnerAccountDetailses() {
        return this.partnerAccountDetailses;
    }
    
    public void setPartnerAccountDetailses(Set partnerAccountDetailses) {
        this.partnerAccountDetailses = partnerAccountDetailses;
    }
    public Set getBikeTransactions() {
        return this.bikeTransactions;
    }
    
    public void setBikeTransactions(Set bikeTransactions) {
        this.bikeTransactions = bikeTransactions;
    }
    public Set getBusDetailses() {
        return this.busDetailses;
    }
    
    public void setBusDetailses(Set busDetailses) {
        this.busDetailses = busDetailses;
    }
    public Set getTaxiDetailses() {
        return this.taxiDetailses;
    }
    
    public void setTaxiDetailses(Set taxiDetailses) {
        this.taxiDetailses = taxiDetailses;
    }
    public Set getShippingTransactions() {
        return this.shippingTransactions;
    }
    
    public void setShippingTransactions(Set shippingTransactions) {
        this.shippingTransactions = shippingTransactions;
    }
    public Set getDriverDetailses() {
        return this.driverDetailses;
    }
    
    public void setDriverDetailses(Set driverDetailses) {
        this.driverDetailses = driverDetailses;
    }
    public Set getBikeDetailses() {
        return this.bikeDetailses;
    }
    
    public void setBikeDetailses(Set bikeDetailses) {
        this.bikeDetailses = bikeDetailses;
    }
    public Set getPartnerRatingDetailses() {
        return this.partnerRatingDetailses;
    }
    
    public void setPartnerRatingDetailses(Set partnerRatingDetailses) {
        this.partnerRatingDetailses = partnerRatingDetailses;
    }
    public Set getBusTransactions() {
        return this.busTransactions;
    }
    
    public void setBusTransactions(Set busTransactions) {
        this.busTransactions = busTransactions;
    }
    public Set getCaronrentTransactions() {
        return this.caronrentTransactions;
    }
    
    public void setCaronrentTransactions(Set caronrentTransactions) {
        this.caronrentTransactions = caronrentTransactions;
    }
    public Set getOutstationTransactions() {
        return this.outstationTransactions;
    }
    
    public void setOutstationTransactions(Set outstationTransactions) {
        this.outstationTransactions = outstationTransactions;
    }
    public Set getAirportTransactions() {
        return this.airportTransactions;
    }
    
    public void setAirportTransactions(Set airportTransactions) {
        this.airportTransactions = airportTransactions;
    }
    public Set getShippingVehicleDetailses() {
        return this.shippingVehicleDetailses;
    }
    
    public void setShippingVehicleDetailses(Set shippingVehicleDetailses) {
        this.shippingVehicleDetailses = shippingVehicleDetailses;
    }
    public Set getPerKgRates() {
        return this.perKgRates;
    }
    
    public void setPerKgRates(Set perKgRates) {
        this.perKgRates = perKgRates;
    }
    public Set getMoversTransactions() {
        return this.moversTransactions;
    }
    
    public void setMoversTransactions(Set moversTransactions) {
        this.moversTransactions = moversTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


