package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * PartnerRatingDetails generated by hbm2java
 */
public class PartnerRatingDetails  extends BaseBean {


     private Integer partnerRatingDetailsId;
     private PartnerDetails partnerDetails;
     private CustomerRegistration customerRegistration;
     private Byte rating;
     private String comment;

    public PartnerRatingDetails() {
    }

	
    public PartnerRatingDetails(PartnerDetails partnerDetails, CustomerRegistration customerRegistration) {
        this.partnerDetails = partnerDetails;
        this.customerRegistration = customerRegistration;
    }
    public PartnerRatingDetails(PartnerDetails partnerDetails, CustomerRegistration customerRegistration, Byte rating, String comment) {
       this.partnerDetails = partnerDetails;
       this.customerRegistration = customerRegistration;
       this.rating = rating;
       this.comment = comment;
    }
   
    public Integer getPartnerRatingDetailsId() {
        return this.partnerRatingDetailsId;
    }
    
    public void setPartnerRatingDetailsId(Integer partnerRatingDetailsId) {
        this.partnerRatingDetailsId = partnerRatingDetailsId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public Byte getRating() {
        return this.rating;
    }
    
    public void setRating(Byte rating) {
        this.rating = rating;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


