package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PerDayRate generated by hbm2java
 */
public class PerDayRate  extends BaseBean {


     private Integer perDayRateId;
     private TaxiDetails taxiDetails;
     private double ratePerDay;
     private Set caronrentTransactions = new HashSet(0);

    public PerDayRate() {
    }

	
    public PerDayRate(TaxiDetails taxiDetails, double ratePerDay) {
        this.taxiDetails = taxiDetails;
        this.ratePerDay = ratePerDay;
    }
    public PerDayRate(TaxiDetails taxiDetails, double ratePerDay, Set caronrentTransactions) {
       this.taxiDetails = taxiDetails;
       this.ratePerDay = ratePerDay;
       this.caronrentTransactions = caronrentTransactions;
    }
   
    public Integer getPerDayRateId() {
        return this.perDayRateId;
    }
    
    public void setPerDayRateId(Integer perDayRateId) {
        this.perDayRateId = perDayRateId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public double getRatePerDay() {
        return this.ratePerDay;
    }
    
    public void setRatePerDay(double ratePerDay) {
        this.ratePerDay = ratePerDay;
    }
    public Set getCaronrentTransactions() {
        return this.caronrentTransactions;
    }
    
    public void setCaronrentTransactions(Set caronrentTransactions) {
        this.caronrentTransactions = caronrentTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


