package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PerHourRate generated by hbm2java
 */
public class PerHourRate  extends BaseBean {


     private Integer perHourRateId;
     private TaxiDetails taxiDetails;
     private double ratePerHour;
     private Set caronrentTransactions = new HashSet(0);

    public PerHourRate() {
    }

	
    public PerHourRate(TaxiDetails taxiDetails, double ratePerHour) {
        this.taxiDetails = taxiDetails;
        this.ratePerHour = ratePerHour;
    }
    public PerHourRate(TaxiDetails taxiDetails, double ratePerHour, Set caronrentTransactions) {
       this.taxiDetails = taxiDetails;
       this.ratePerHour = ratePerHour;
       this.caronrentTransactions = caronrentTransactions;
    }
   
    public Integer getPerHourRateId() {
        return this.perHourRateId;
    }
    
    public void setPerHourRateId(Integer perHourRateId) {
        this.perHourRateId = perHourRateId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public double getRatePerHour() {
        return this.ratePerHour;
    }
    
    public void setRatePerHour(double ratePerHour) {
        this.ratePerHour = ratePerHour;
    }
    public Set getCaronrentTransactions() {
        return this.caronrentTransactions;
    }
    
    public void setCaronrentTransactions(Set caronrentTransactions) {
        this.caronrentTransactions = caronrentTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


