package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PerKgRate generated by hbm2java
 */
public class PerKgRate  extends BaseBean {


     private Integer perKgRateId;
     private PartnerDetails partnerDetails;
     private String perKgRate;
     private Set moversRates = new HashSet(0);

    public PerKgRate() {
    }

	
    public PerKgRate(PartnerDetails partnerDetails, String perKgRate) {
        this.partnerDetails = partnerDetails;
        this.perKgRate = perKgRate;
    }
    public PerKgRate(PartnerDetails partnerDetails, String perKgRate, Set moversRates) {
       this.partnerDetails = partnerDetails;
       this.perKgRate = perKgRate;
       this.moversRates = moversRates;
    }
   
    public Integer getPerKgRateId() {
        return this.perKgRateId;
    }
    
    public void setPerKgRateId(Integer perKgRateId) {
        this.perKgRateId = perKgRateId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public String getPerKgRate() {
        return this.perKgRate;
    }
    
    public void setPerKgRate(String perKgRate) {
        this.perKgRate = perKgRate;
    }
    public Set getMoversRates() {
        return this.moversRates;
    }
    
    public void setMoversRates(Set moversRates) {
        this.moversRates = moversRates;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


