package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * PerKmRate generated by hbm2java
 */
public class PerKmRate  extends BaseBean {


     private Integer perKmRateId;
     private TaxiDetails taxiDetails;
     private TaxiType taxiType;
     private double ratePerKm;
     private double minRate;
     private double waitingCharge;
     private double driverCost;
     private Set packageTaxis = new HashSet(0);
     private Set tourTaxis = new HashSet(0);
     private Set moversRates = new HashSet(0);
     private Set ptopTaxis = new HashSet(0);
     private Set caronrentTransactions = new HashSet(0);
     private Set airportTaxis = new HashSet(0);

    public PerKmRate() {
    }

	
    public PerKmRate(TaxiDetails taxiDetails, TaxiType taxiType, double ratePerKm, double minRate, double waitingCharge, double driverCost) {
        this.taxiDetails = taxiDetails;
        this.taxiType = taxiType;
        this.ratePerKm = ratePerKm;
        this.minRate = minRate;
        this.waitingCharge = waitingCharge;
        this.driverCost = driverCost;
    }
    public PerKmRate(TaxiDetails taxiDetails, TaxiType taxiType, double ratePerKm, double minRate, double waitingCharge, double driverCost, Set packageTaxis, Set tourTaxis, Set moversRates, Set ptopTaxis, Set caronrentTransactions, Set airportTaxis) {
       this.taxiDetails = taxiDetails;
       this.taxiType = taxiType;
       this.ratePerKm = ratePerKm;
       this.minRate = minRate;
       this.waitingCharge = waitingCharge;
       this.driverCost = driverCost;
       this.packageTaxis = packageTaxis;
       this.tourTaxis = tourTaxis;
       this.moversRates = moversRates;
       this.ptopTaxis = ptopTaxis;
       this.caronrentTransactions = caronrentTransactions;
       this.airportTaxis = airportTaxis;
    }
   
    public Integer getPerKmRateId() {
        return this.perKmRateId;
    }
    
    public void setPerKmRateId(Integer perKmRateId) {
        this.perKmRateId = perKmRateId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public TaxiType getTaxiType() {
        return this.taxiType;
    }
    
    public void setTaxiType(TaxiType taxiType) {
        this.taxiType = taxiType;
    }
    public double getRatePerKm() {
        return this.ratePerKm;
    }
    
    public void setRatePerKm(double ratePerKm) {
        this.ratePerKm = ratePerKm;
    }
    public double getMinRate() {
        return this.minRate;
    }
    
    public void setMinRate(double minRate) {
        this.minRate = minRate;
    }
    public double getWaitingCharge() {
        return this.waitingCharge;
    }
    
    public void setWaitingCharge(double waitingCharge) {
        this.waitingCharge = waitingCharge;
    }
    public double getDriverCost() {
        return this.driverCost;
    }
    
    public void setDriverCost(double driverCost) {
        this.driverCost = driverCost;
    }
    public Set getPackageTaxis() {
        return this.packageTaxis;
    }
    
    public void setPackageTaxis(Set packageTaxis) {
        this.packageTaxis = packageTaxis;
    }
    public Set getTourTaxis() {
        return this.tourTaxis;
    }
    
    public void setTourTaxis(Set tourTaxis) {
        this.tourTaxis = tourTaxis;
    }
    public Set getMoversRates() {
        return this.moversRates;
    }
    
    public void setMoversRates(Set moversRates) {
        this.moversRates = moversRates;
    }
    public Set getPtopTaxis() {
        return this.ptopTaxis;
    }
    
    public void setPtopTaxis(Set ptopTaxis) {
        this.ptopTaxis = ptopTaxis;
    }
    public Set getCaronrentTransactions() {
        return this.caronrentTransactions;
    }
    
    public void setCaronrentTransactions(Set caronrentTransactions) {
        this.caronrentTransactions = caronrentTransactions;
    }
    public Set getAirportTaxis() {
        return this.airportTaxis;
    }
    
    public void setAirportTaxis(Set airportTaxis) {
        this.airportTaxis = airportTaxis;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


