package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * PlaceMaster generated by hbm2java
 */
public class PlaceMaster  extends BaseBean {


     private Integer placeMasterId;
     private CityMaster cityMaster;
     private StateMaster stateMaster;
     private String placeName;
     private String longitude;
     private String latitude;

    public PlaceMaster() {
    }

	
    public PlaceMaster(CityMaster cityMaster, StateMaster stateMaster, String placeName) {
        this.cityMaster = cityMaster;
        this.stateMaster = stateMaster;
        this.placeName = placeName;
    }
    public PlaceMaster(CityMaster cityMaster, StateMaster stateMaster, String placeName, String longitude, String latitude) {
       this.cityMaster = cityMaster;
       this.stateMaster = stateMaster;
       this.placeName = placeName;
       this.longitude = longitude;
       this.latitude = latitude;
    }
   
    public Integer getPlaceMasterId() {
        return this.placeMasterId;
    }
    
    public void setPlaceMasterId(Integer placeMasterId) {
        this.placeMasterId = placeMasterId;
    }
    public CityMaster getCityMaster() {
        return this.cityMaster;
    }
    
    public void setCityMaster(CityMaster cityMaster) {
        this.cityMaster = cityMaster;
    }
    public StateMaster getStateMaster() {
        return this.stateMaster;
    }
    
    public void setStateMaster(StateMaster stateMaster) {
        this.stateMaster = stateMaster;
    }
    public String getPlaceName() {
        return this.placeName;
    }
    
    public void setPlaceName(String placeName) {
        this.placeName = placeName;
    }
    public String getLongitude() {
        return this.longitude;
    }
    
    public void setLongitude(String longitude) {
        this.longitude = longitude;
    }
    public String getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(String latitude) {
        this.latitude = latitude;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


