package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * PtopTaxi generated by hbm2java
 */
public class PtopTaxi  extends BaseBean {


     private Integer ptopTaxiId;
     private PerKmRate perKmRate;

    public PtopTaxi() {
    }

    public PtopTaxi(PerKmRate perKmRate) {
       this.perKmRate = perKmRate;
    }
   
    public Integer getPtopTaxiId() {
        return this.ptopTaxiId;
    }
    
    public void setPtopTaxiId(Integer ptopTaxiId) {
        this.ptopTaxiId = ptopTaxiId;
    }
    public PerKmRate getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(PerKmRate perKmRate) {
        this.perKmRate = perKmRate;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


