package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * ShippingVehicleDetails generated by hbm2java
 */
public class ShippingVehicleDetails  extends BaseBean {


     private Integer shippingVehicleDetailsId;
     private ShippingVehicleType shippingVehicleType;
     private PartnerDetails partnerDetails;
     private String name;
     private String shippingVehicleNo;
     private int capacity;
     private double perKmRate;
     private double perKgRate;
     private String shippingVehicleImage;
     private Double perDayRate;
     private String note;

    public ShippingVehicleDetails() {
    }

	
    public ShippingVehicleDetails(ShippingVehicleType shippingVehicleType, PartnerDetails partnerDetails, String name, String shippingVehicleNo, int capacity, double perKmRate, double perKgRate) {
        this.shippingVehicleType = shippingVehicleType;
        this.partnerDetails = partnerDetails;
        this.name = name;
        this.shippingVehicleNo = shippingVehicleNo;
        this.capacity = capacity;
        this.perKmRate = perKmRate;
        this.perKgRate = perKgRate;
    }
    public ShippingVehicleDetails(ShippingVehicleType shippingVehicleType, PartnerDetails partnerDetails, String name, String shippingVehicleNo, int capacity, double perKmRate, double perKgRate, String shippingVehicleImage, Double perDayRate, String note) {
       this.shippingVehicleType = shippingVehicleType;
       this.partnerDetails = partnerDetails;
       this.name = name;
       this.shippingVehicleNo = shippingVehicleNo;
       this.capacity = capacity;
       this.perKmRate = perKmRate;
       this.perKgRate = perKgRate;
       this.shippingVehicleImage = shippingVehicleImage;
       this.perDayRate = perDayRate;
       this.note = note;
    }
   
    public Integer getShippingVehicleDetailsId() {
        return this.shippingVehicleDetailsId;
    }
    
    public void setShippingVehicleDetailsId(Integer shippingVehicleDetailsId) {
        this.shippingVehicleDetailsId = shippingVehicleDetailsId;
    }
    public ShippingVehicleType getShippingVehicleType() {
        return this.shippingVehicleType;
    }
    
    public void setShippingVehicleType(ShippingVehicleType shippingVehicleType) {
        this.shippingVehicleType = shippingVehicleType;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getShippingVehicleNo() {
        return this.shippingVehicleNo;
    }
    
    public void setShippingVehicleNo(String shippingVehicleNo) {
        this.shippingVehicleNo = shippingVehicleNo;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public double getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(double perKmRate) {
        this.perKmRate = perKmRate;
    }
    public double getPerKgRate() {
        return this.perKgRate;
    }
    
    public void setPerKgRate(double perKgRate) {
        this.perKgRate = perKgRate;
    }
    public String getShippingVehicleImage() {
        return this.shippingVehicleImage;
    }
    
    public void setShippingVehicleImage(String shippingVehicleImage) {
        this.shippingVehicleImage = shippingVehicleImage;
    }
    public Double getPerDayRate() {
        return this.perDayRate;
    }
    
    public void setPerDayRate(Double perDayRate) {
        this.perDayRate = perDayRate;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


