package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * ShippingVehicleType generated by hbm2java
 */
public class ShippingVehicleType  extends BaseBean {


     private Integer shippingVehicleTypeId;
     private String shippingVehicleType;
     private Set shippingVehicleDetailses = new HashSet(0);

    public ShippingVehicleType() {
    }

	
    public ShippingVehicleType(String shippingVehicleType) {
        this.shippingVehicleType = shippingVehicleType;
    }
    public ShippingVehicleType(String shippingVehicleType, Set shippingVehicleDetailses) {
       this.shippingVehicleType = shippingVehicleType;
       this.shippingVehicleDetailses = shippingVehicleDetailses;
    }
   
    public Integer getShippingVehicleTypeId() {
        return this.shippingVehicleTypeId;
    }
    
    public void setShippingVehicleTypeId(Integer shippingVehicleTypeId) {
        this.shippingVehicleTypeId = shippingVehicleTypeId;
    }
    public String getShippingVehicleType() {
        return this.shippingVehicleType;
    }
    
    public void setShippingVehicleType(String shippingVehicleType) {
        this.shippingVehicleType = shippingVehicleType;
    }
    public Set getShippingVehicleDetailses() {
        return this.shippingVehicleDetailses;
    }
    
    public void setShippingVehicleDetailses(Set shippingVehicleDetailses) {
        this.shippingVehicleDetailses = shippingVehicleDetailses;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


