package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ShippingTransaction generated by hbm2java
 */
public class ShippingTransaction  extends BaseBean {


     private Integer shippingTransactionId;
     private GoodsType goodsType;
     private CityMaster cityMasterByStartCityId;
     private CityMaster cityMasterByEndCityId;
     private PartnerDetails partnerDetails;
     private CustomerRegistration customerRegistration;
     private Date date;
     private Date time;
     private double estimateKm;
     private double estimateCost;
     private double weight;
     private String startAddress;
     private String dropAddress;
     private int driverDetailsId;
     private Set commitShippingTransactions = new HashSet(0);

    public ShippingTransaction() {
    }

	
    public ShippingTransaction(GoodsType goodsType, CityMaster cityMasterByStartCityId, CityMaster cityMasterByEndCityId, PartnerDetails partnerDetails, CustomerRegistration customerRegistration, Date date, Date time, double estimateKm, double estimateCost, double weight, String startAddress, String dropAddress, int driverDetailsId) {
        this.goodsType = goodsType;
        this.cityMasterByStartCityId = cityMasterByStartCityId;
        this.cityMasterByEndCityId = cityMasterByEndCityId;
        this.partnerDetails = partnerDetails;
        this.customerRegistration = customerRegistration;
        this.date = date;
        this.time = time;
        this.estimateKm = estimateKm;
        this.estimateCost = estimateCost;
        this.weight = weight;
        this.startAddress = startAddress;
        this.dropAddress = dropAddress;
        this.driverDetailsId = driverDetailsId;
    }
    public ShippingTransaction(GoodsType goodsType, CityMaster cityMasterByStartCityId, CityMaster cityMasterByEndCityId, PartnerDetails partnerDetails, CustomerRegistration customerRegistration, Date date, Date time, double estimateKm, double estimateCost, double weight, String startAddress, String dropAddress, int driverDetailsId, Set commitShippingTransactions) {
       this.goodsType = goodsType;
       this.cityMasterByStartCityId = cityMasterByStartCityId;
       this.cityMasterByEndCityId = cityMasterByEndCityId;
       this.partnerDetails = partnerDetails;
       this.customerRegistration = customerRegistration;
       this.date = date;
       this.time = time;
       this.estimateKm = estimateKm;
       this.estimateCost = estimateCost;
       this.weight = weight;
       this.startAddress = startAddress;
       this.dropAddress = dropAddress;
       this.driverDetailsId = driverDetailsId;
       this.commitShippingTransactions = commitShippingTransactions;
    }
   
    public Integer getShippingTransactionId() {
        return this.shippingTransactionId;
    }
    
    public void setShippingTransactionId(Integer shippingTransactionId) {
        this.shippingTransactionId = shippingTransactionId;
    }
    public GoodsType getGoodsType() {
        return this.goodsType;
    }
    
    public void setGoodsType(GoodsType goodsType) {
        this.goodsType = goodsType;
    }
    public CityMaster getCityMasterByStartCityId() {
        return this.cityMasterByStartCityId;
    }
    
    public void setCityMasterByStartCityId(CityMaster cityMasterByStartCityId) {
        this.cityMasterByStartCityId = cityMasterByStartCityId;
    }
    public CityMaster getCityMasterByEndCityId() {
        return this.cityMasterByEndCityId;
    }
    
    public void setCityMasterByEndCityId(CityMaster cityMasterByEndCityId) {
        this.cityMasterByEndCityId = cityMasterByEndCityId;
    }
    public PartnerDetails getPartnerDetails() {
        return this.partnerDetails;
    }
    
    public void setPartnerDetails(PartnerDetails partnerDetails) {
        this.partnerDetails = partnerDetails;
    }
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Date getTime() {
        return this.time;
    }
    
    public void setTime(Date time) {
        this.time = time;
    }
    public double getEstimateKm() {
        return this.estimateKm;
    }
    
    public void setEstimateKm(double estimateKm) {
        this.estimateKm = estimateKm;
    }
    public double getEstimateCost() {
        return this.estimateCost;
    }
    
    public void setEstimateCost(double estimateCost) {
        this.estimateCost = estimateCost;
    }
    public double getWeight() {
        return this.weight;
    }
    
    public void setWeight(double weight) {
        this.weight = weight;
    }
    public String getStartAddress() {
        return this.startAddress;
    }
    
    public void setStartAddress(String startAddress) {
        this.startAddress = startAddress;
    }
    public String getDropAddress() {
        return this.dropAddress;
    }
    
    public void setDropAddress(String dropAddress) {
        this.dropAddress = dropAddress;
    }
    public int getDriverDetailsId() {
        return this.driverDetailsId;
    }
    
    public void setDriverDetailsId(int driverDetailsId) {
        this.driverDetailsId = driverDetailsId;
    }
    public Set getCommitShippingTransactions() {
        return this.commitShippingTransactions;
    }
    
    public void setCommitShippingTransactions(Set commitShippingTransactions) {
        this.commitShippingTransactions = commitShippingTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


