package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * StateMaster generated by hbm2java
 */
public class StateMaster  extends BaseBean {


     private Integer stateMasterId;
     private String stateName;
     private Set cityMasters = new HashSet(0);
     private Set placeMasters = new HashSet(0);

    public StateMaster() {
    }

	
    public StateMaster(String stateName) {
        this.stateName = stateName;
    }
    public StateMaster(String stateName, Set cityMasters, Set placeMasters) {
       this.stateName = stateName;
       this.cityMasters = cityMasters;
       this.placeMasters = placeMasters;
    }
   
    public Integer getStateMasterId() {
        return this.stateMasterId;
    }
    
    public void setStateMasterId(Integer stateMasterId) {
        this.stateMasterId = stateMasterId;
    }
    public String getStateName() {
        return this.stateName;
    }
    
    public void setStateName(String stateName) {
        this.stateName = stateName;
    }
    public Set getCityMasters() {
        return this.cityMasters;
    }
    
    public void setCityMasters(Set cityMasters) {
        this.cityMasters = cityMasters;
    }
    public Set getPlaceMasters() {
        return this.placeMasters;
    }
    
    public void setPlaceMasters(Set placeMasters) {
        this.placeMasters = placeMasters;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


