package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * TaxiAvailability generated by hbm2java
 */
public class TaxiAvailability  extends BaseBean {


     private Integer taxiAvailabilityId;
     private TaxiDetails taxiDetails;
     private byte forPtop;
     private byte forPackage;
     private byte forOutstation;
     private byte forAirport;
     private byte forTaxiticket;
     private byte forCaronrent;

    public TaxiAvailability() {
    }

    public TaxiAvailability(TaxiDetails taxiDetails, byte forPtop, byte forPackage, byte forOutstation, byte forAirport, byte forTaxiticket, byte forCaronrent) {
       this.taxiDetails = taxiDetails;
       this.forPtop = forPtop;
       this.forPackage = forPackage;
       this.forOutstation = forOutstation;
       this.forAirport = forAirport;
       this.forTaxiticket = forTaxiticket;
       this.forCaronrent = forCaronrent;
    }
   
    public Integer getTaxiAvailabilityId() {
        return this.taxiAvailabilityId;
    }
    
    public void setTaxiAvailabilityId(Integer taxiAvailabilityId) {
        this.taxiAvailabilityId = taxiAvailabilityId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public byte getForPtop() {
        return this.forPtop;
    }
    
    public void setForPtop(byte forPtop) {
        this.forPtop = forPtop;
    }
    public byte getForPackage() {
        return this.forPackage;
    }
    
    public void setForPackage(byte forPackage) {
        this.forPackage = forPackage;
    }
    public byte getForOutstation() {
        return this.forOutstation;
    }
    
    public void setForOutstation(byte forOutstation) {
        this.forOutstation = forOutstation;
    }
    public byte getForAirport() {
        return this.forAirport;
    }
    
    public void setForAirport(byte forAirport) {
        this.forAirport = forAirport;
    }
    public byte getForTaxiticket() {
        return this.forTaxiticket;
    }
    
    public void setForTaxiticket(byte forTaxiticket) {
        this.forTaxiticket = forTaxiticket;
    }
    public byte getForCaronrent() {
        return this.forCaronrent;
    }
    
    public void setForCaronrent(byte forCaronrent) {
        this.forCaronrent = forCaronrent;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


