package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * TaxiAmenities generated by hbm2java
 */
public class TaxiAmenities  extends BaseBean {


     private Integer taxiAmenitiesId;
     private TaxiDetails taxiDetails;
     private boolean isAc;
     private boolean isMovie;
     private boolean isMusic;
     private boolean isCharger;
     private boolean isWifi;
     private boolean isNewspaper;

    public TaxiAmenities() {
    }

    public TaxiAmenities(TaxiDetails taxiDetails, boolean isAc, boolean isMovie, boolean isMusic, boolean isCharger, boolean isWifi, boolean isNewspaper) {
       this.taxiDetails = taxiDetails;
       this.isAc = isAc;
       this.isMovie = isMovie;
       this.isMusic = isMusic;
       this.isCharger = isCharger;
       this.isWifi = isWifi;
       this.isNewspaper = isNewspaper;
    }
   
    public Integer getTaxiAmenitiesId() {
        return this.taxiAmenitiesId;
    }
    
    public void setTaxiAmenitiesId(Integer taxiAmenitiesId) {
        this.taxiAmenitiesId = taxiAmenitiesId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public boolean isIsAc() {
        return this.isAc;
    }
    
    public void setIsAc(boolean isAc) {
        this.isAc = isAc;
    }
    public boolean isIsMovie() {
        return this.isMovie;
    }
    
    public void setIsMovie(boolean isMovie) {
        this.isMovie = isMovie;
    }
    public boolean isIsMusic() {
        return this.isMusic;
    }
    
    public void setIsMusic(boolean isMusic) {
        this.isMusic = isMusic;
    }
    public boolean isIsCharger() {
        return this.isCharger;
    }
    
    public void setIsCharger(boolean isCharger) {
        this.isCharger = isCharger;
    }
    public boolean isIsWifi() {
        return this.isWifi;
    }
    
    public void setIsWifi(boolean isWifi) {
        this.isWifi = isWifi;
    }
    public boolean isIsNewspaper() {
        return this.isNewspaper;
    }
    
    public void setIsNewspaper(boolean isNewspaper) {
        this.isNewspaper = isNewspaper;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


