package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TaxiTicketTransaction generated by hbm2java
 */
public class TaxiTicketTransaction  extends BaseBean {


     private Integer taxiTicketTrasactionId;
     private TaxiDetails taxiDetails;
     private CityMaster cityMasterByEndCityMasterId;
     private AreaMaster areaMaster;
     private CityMaster cityMasterByStartCityMasterId;
     private int seatAvailable;
     private Date pickupTime;
     private String pickupAddress;
     private Set commitTaxiTicketTransactions = new HashSet(0);

    public TaxiTicketTransaction() {
    }

	
    public TaxiTicketTransaction(TaxiDetails taxiDetails, CityMaster cityMasterByEndCityMasterId, AreaMaster areaMaster, CityMaster cityMasterByStartCityMasterId, int seatAvailable, Date pickupTime, String pickupAddress) {
        this.taxiDetails = taxiDetails;
        this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
        this.areaMaster = areaMaster;
        this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
        this.seatAvailable = seatAvailable;
        this.pickupTime = pickupTime;
        this.pickupAddress = pickupAddress;
    }
    public TaxiTicketTransaction(TaxiDetails taxiDetails, CityMaster cityMasterByEndCityMasterId, AreaMaster areaMaster, CityMaster cityMasterByStartCityMasterId, int seatAvailable, Date pickupTime, String pickupAddress, Set commitTaxiTicketTransactions) {
       this.taxiDetails = taxiDetails;
       this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
       this.areaMaster = areaMaster;
       this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
       this.seatAvailable = seatAvailable;
       this.pickupTime = pickupTime;
       this.pickupAddress = pickupAddress;
       this.commitTaxiTicketTransactions = commitTaxiTicketTransactions;
    }
   
    public Integer getTaxiTicketTrasactionId() {
        return this.taxiTicketTrasactionId;
    }
    
    public void setTaxiTicketTrasactionId(Integer taxiTicketTrasactionId) {
        this.taxiTicketTrasactionId = taxiTicketTrasactionId;
    }
    public TaxiDetails getTaxiDetails() {
        return this.taxiDetails;
    }
    
    public void setTaxiDetails(TaxiDetails taxiDetails) {
        this.taxiDetails = taxiDetails;
    }
    public CityMaster getCityMasterByEndCityMasterId() {
        return this.cityMasterByEndCityMasterId;
    }
    
    public void setCityMasterByEndCityMasterId(CityMaster cityMasterByEndCityMasterId) {
        this.cityMasterByEndCityMasterId = cityMasterByEndCityMasterId;
    }
    public AreaMaster getAreaMaster() {
        return this.areaMaster;
    }
    
    public void setAreaMaster(AreaMaster areaMaster) {
        this.areaMaster = areaMaster;
    }
    public CityMaster getCityMasterByStartCityMasterId() {
        return this.cityMasterByStartCityMasterId;
    }
    
    public void setCityMasterByStartCityMasterId(CityMaster cityMasterByStartCityMasterId) {
        this.cityMasterByStartCityMasterId = cityMasterByStartCityMasterId;
    }
    public int getSeatAvailable() {
        return this.seatAvailable;
    }
    
    public void setSeatAvailable(int seatAvailable) {
        this.seatAvailable = seatAvailable;
    }
    public Date getPickupTime() {
        return this.pickupTime;
    }
    
    public void setPickupTime(Date pickupTime) {
        this.pickupTime = pickupTime;
    }
    public String getPickupAddress() {
        return this.pickupAddress;
    }
    
    public void setPickupAddress(String pickupAddress) {
        this.pickupAddress = pickupAddress;
    }
    public Set getCommitTaxiTicketTransactions() {
        return this.commitTaxiTicketTransactions;
    }
    
    public void setCommitTaxiTicketTransactions(Set commitTaxiTicketTransactions) {
        this.commitTaxiTicketTransactions = commitTaxiTicketTransactions;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


