package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * TaxiType generated by hbm2java
 */
public class TaxiType  extends BaseBean {


     private Integer taxiTypeId;
     private String taxiType;
     private int seat;
     private String description;
     private int maxPassengerAllow;
     private Set perKmRates = new HashSet(0);
     private Set taxiDetailses = new HashSet(0);

    public TaxiType() {
    }

	
    public TaxiType(String taxiType, int seat, String description, int maxPassengerAllow) {
        this.taxiType = taxiType;
        this.seat = seat;
        this.description = description;
        this.maxPassengerAllow = maxPassengerAllow;
    }
    public TaxiType(String taxiType, int seat, String description, int maxPassengerAllow, Set perKmRates, Set taxiDetailses) {
       this.taxiType = taxiType;
       this.seat = seat;
       this.description = description;
       this.maxPassengerAllow = maxPassengerAllow;
       this.perKmRates = perKmRates;
       this.taxiDetailses = taxiDetailses;
    }
   
    public Integer getTaxiTypeId() {
        return this.taxiTypeId;
    }
    
    public void setTaxiTypeId(Integer taxiTypeId) {
        this.taxiTypeId = taxiTypeId;
    }
    public String getTaxiType() {
        return this.taxiType;
    }
    
    public void setTaxiType(String taxiType) {
        this.taxiType = taxiType;
    }
    public int getSeat() {
        return this.seat;
    }
    
    public void setSeat(int seat) {
        this.seat = seat;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public int getMaxPassengerAllow() {
        return this.maxPassengerAllow;
    }
    
    public void setMaxPassengerAllow(int maxPassengerAllow) {
        this.maxPassengerAllow = maxPassengerAllow;
    }
    public Set getPerKmRates() {
        return this.perKmRates;
    }
    
    public void setPerKmRates(Set perKmRates) {
        this.perKmRates = perKmRates;
    }
    public Set getTaxiDetailses() {
        return this.taxiDetailses;
    }
    
    public void setTaxiDetailses(Set taxiDetailses) {
        this.taxiDetailses = taxiDetailses;
    }


	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


