package hibernate.bean;
// Generated 7 Oct, 2014 5:35:30 PM by Hibernate Tools 3.6.0



/**
 * TourTaxi generated by hbm2java
 */
public class TourTaxi  extends BaseBean {


     private Integer tourTaxiId;
     private PerKmRate perKmRate;

    public TourTaxi() {
    }

    public TourTaxi(PerKmRate perKmRate) {
       this.perKmRate = perKmRate;
    }
   
    public Integer getTourTaxiId() {
        return this.tourTaxiId;
    }
    
    public void setTourTaxiId(Integer tourTaxiId) {
        this.tourTaxiId = tourTaxiId;
    }
    public PerKmRate getPerKmRate() {
        return this.perKmRate;
    }
    
    public void setPerKmRate(PerKmRate perKmRate) {
        this.perKmRate = perKmRate;
    }

	@Override
	public boolean validateBean(StringBuffer messageOfValidation) {
		// TODO Auto-generated method stub
		return false;
	}




}


